"""
Monitor-specific SQLAlchemy ORM models.

Provides two tables:
- MonitorEvent: Individual pipeline events (detailed, retained for MONITOR_DETAIL_WINDOW_DAYS)
- MonitorDailySummary: Aggregated daily summaries (retained indefinitely)

These tables live in the same SQLite database as the main POC tables.
The monitor backend reads existing POC tables (evaluations, jobs, issues, metric_results)
and reads/writes its own monitor tables.
"""

from datetime import date, datetime, timezone

from sqlalchemy import (
    BigInteger, Boolean, Column, Date, DateTime, Float,
    Integer, String, Text,
)

from core.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class MonitorEvent(Base):
    """
    Individual pipeline event — detailed telemetry.

    Retained for MONITOR_DETAIL_WINDOW_DAYS (default 30 days),
    then aggregated into MonitorDailySummary and pruned.
    """

    __tablename__ = "monitor_events"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    timestamp: datetime = Column(DateTime, nullable=False, default=_utcnow, index=True)
    workspace: str = Column(String(20), nullable=False)  # "banking" | "compliance"
    event_type: str = Column(String(50), nullable=False, index=True)
    # event_type values:
    #   "llm_call"       — individual LLM API call
    #   "eval_start"     — evaluation pipeline started
    #   "eval_complete"  — evaluation pipeline finished successfully
    #   "eval_error"     — evaluation pipeline failed
    #   "pipeline_step"  — individual pipeline step completed
    #   "upload"         — file uploaded for evaluation

    evaluation_id: str = Column(String(36), nullable=True)
    job_id: str = Column(String(36), nullable=True)

    # LLM telemetry (populated for event_type="llm_call")
    llm_model: str = Column(String(100), nullable=True)
    llm_latency_ms: int = Column(Integer, nullable=True)
    llm_input_tokens: int = Column(Integer, nullable=True)
    llm_output_tokens: int = Column(Integer, nullable=True)
    llm_status_code: int = Column(Integer, nullable=True)
    llm_error: str = Column(Text, nullable=True)

    # Pipeline step tracking (populated for event_type="pipeline_step")
    pipeline_step: str = Column(String(50), nullable=True)
    step_latency_ms: int = Column(Integer, nullable=True)

    # Document metadata (populated for event_type="eval_start" / "upload")
    filename: str = Column(String(255), nullable=True)
    file_size_bytes: int = Column(BigInteger, nullable=True)

    # Evaluation result (populated for event_type="eval_complete")
    overall_score: float = Column(Float, nullable=True)
    banking_domain: str = Column(String(100), nullable=True)

    # Flexible extra data (JSON string for niche metrics)
    extra_json: str = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<MonitorEvent(id={self.id}, type={self.event_type}, ws={self.workspace})>"


class MonitorDailySummary(Base):
    """
    Aggregated daily summary — retained indefinitely.

    Generated by the AggregationService when detailed events
    are older than MONITOR_DETAIL_WINDOW_DAYS.
    """

    __tablename__ = "monitor_daily_summaries"

    id: int = Column(Integer, primary_key=True, autoincrement=True)
    summary_date: date = Column(Date, nullable=False, index=True)
    workspace: str = Column(String(20), nullable=False)

    # Evaluation stats
    eval_count: int = Column(Integer, nullable=False, default=0)
    eval_success: int = Column(Integer, nullable=False, default=0)
    eval_failed: int = Column(Integer, nullable=False, default=0)
    avg_overall_score: float = Column(Float, nullable=True)
    min_score: float = Column(Float, nullable=True)
    max_score: float = Column(Float, nullable=True)
    # JSON: {"0-10": 1, "10-20": 3, "20-30": 0, ...}
    score_histogram_json: str = Column(Text, nullable=True)

    # LLM stats
    llm_call_count: int = Column(Integer, nullable=False, default=0)
    llm_avg_latency_ms: int = Column(Integer, nullable=True)
    llm_p90_latency_ms: int = Column(Integer, nullable=True)
    llm_total_input_tokens: int = Column(BigInteger, nullable=False, default=0)
    llm_total_output_tokens: int = Column(BigInteger, nullable=False, default=0)
    llm_error_count: int = Column(Integer, nullable=False, default=0)

    # Issue stats
    issues_critical: int = Column(Integer, nullable=False, default=0)
    issues_warning: int = Column(Integer, nullable=False, default=0)
    legal_hold_count: int = Column(Integer, nullable=False, default=0)

    # Pipeline stats
    avg_pipeline_duration_ms: int = Column(Integer, nullable=True)

    # Top recurring issues (JSON array of {"description": ..., "count": ...})
    top_issues_json: str = Column(Text, nullable=True)

    # Domain breakdown (JSON: {"Customer Onboarding (KYC/AML)": 3, "Loan & Credit Documentation": 2})
    domain_breakdown_json: str = Column(Text, nullable=True)

    def __repr__(self) -> str:
        return f"<MonitorDailySummary(date={self.summary_date}, ws={self.workspace})>"
